### PR TITLE
Drop tables in an order considering foreign key constraints

### PR DESCRIPTION
**Pull request by abicky**
This PR resolves https://github.com/winebarrel/ridgepole/issues/283.

### CODE REVIEW

**Comment by abicky** [comment]
@winebarrel May I merge this PR and release a new version 0.8.1 like a commit https://github.com/winebarrel/ridgepole/commit/9a69558bd334685f4df014de7c67a8cbe3430a58 (including publishing to RubyGems.org)?

**Comment by winebarrel** [comment]
> May I merge this PR and release a new version 0.8.1 like a commit 9a69558 (including publishing to RubyGems.org)?

Yes!
LGTM! Thank you! 👍

**Comment by abicky** [comment]
Thank you! I'll release a new version :)

**Comment by abicky** [comment]
I've released v0.8.1.

**Pull request merged**
