### PR TITLE
[Fix] warning message for options scanning

### PR DESCRIPTION
**Pull request by timakin**
@winebarrel 
Fixed this issue, please check this.
https://github.com/winebarrel/ridgepole/issues/59

### CODE REVIEW

**Comment by winebarrel** [comment]
Thanks for your PR :+1:

**Comment by winebarrel** [comment]
@timakin Please fix warning messege test (see migrate_change_table_option_spec.rb).

**Comment by timakin** [comment]
sorry, I'll fix it asap.

**Comment by winebarrel** [comment]
LGTM!
Thank you!

**Pull request merged**
